### ISSUE TITLE
GPU miner error 9

### ISSUE THREAD

**Issue by Pdpe** [VeriBlock/nodecore-pow-cuda-miner#1]
When GPU miner loses connection with pool for some period of time, error 9 submitting shares persists until manual restart of miner instance.

**Comment by reb0rn21** [comment]
same here... also if pool refuse miner connection miner just wait there and ask enter to be pressed for exit, which is also bad as loop scrypt is stoped there

**Comment by NxtGenCowboy** [comment]
Mine does the same. I have had it happen randomly as well, even if the pool didn't go down.  The only other thing I can think of for myself, is another wallet interfering.

**Comment by timstall** [comment]
This appears solved with issues from 0.3.11
