### ISSUE TITLE
Miner freeze with no error

### ISSUE THREAD

**Issue by Alixbui** [VeriBlock/nodecore-pow-cuda-miner#2]
It's happen 9/10 times my miner freeze with no errors message and no logs juste stop to run. I'm on 1070 and cuda 9.2. Sometimes it stops within 20min, sometimes some hours.

**Comment by huglester** [comment]
some people say, that for them it freezes on DHCP renew

**Comment by timstall** [comment]
Released 0.3.7

**Comment by timstall** [comment]
This appears solved with the many community contributions rolled into 0.3.11. Can open new issues as needed.
